/*
 * @author Jordon m
 * @date 2022-01-19
 * @class name: FXMLDocumentController
 * @description: This class contains all the code when the user interacts with the GUI
 */


//Importing all the nessary libaries for JAVA FX
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;

//Implements mean that we are using an interface in the class
public class FXMLDocumentController implements Initializable {
    
    //@FXML is used to tag a non public stuff for use by the FXML documnet
    @FXML

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // TODO
    }    
    
    //the following methods were automaticly generated by JAVA FX screen buidler
    @FXML
    
    /**
     * @method name: handlerGeneralAction
     * @Discription: This method holds all the code that is to be excuted once the user clicks a General action button
     */
    private void handlerGeneralAction(ActionEvent event) {

    }

    @FXML
    /**
     * @method name: handlerDigitAction
     * @Discription: This method holds all the code that is to be excuted once the user clicks a digit
     */
    private void handlerDigitAction(ActionEvent event) {

    }
    
    /**
     * @method name: handlerDecimalAction
     * @Discription: This method holds all the code that is to be excuted once the user clicks a decimal button
     */
    @FXML
    private void handlerDecimalAction(ActionEvent event) {

    }
    
    /**
     * @method name: handlerEqualAction
     * @Discription: This method holds all the code that is to be excuted once the user clicks a equal button
     */
    @FXML
    private void handlerEqualAction(ActionEvent event) {

        
    }
    
}
